name: Build XBPS Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86_64, x86_64-musl, aarch64, aarch64-musl]

    env:
      TARGET_ARCH: ${{ matrix.arch }}
      SCRIPT_DIR: scripts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x ${{ env.SCRIPT_DIR }}/*

      - name: Prepare environment
        run: ${{ env.SCRIPT_DIR }}/set-environment

      - name: Build changed packages
        run: ${{ env.SCRIPT_DIR }}/build-packages

      - name: Push compiled packages
        run: ${{ env.SCRIPT_DIR }}/push-repository
