name: Build XBPS Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86_64, x86_64-musl, aarch64, aarch64-musl]

    env:
      TARGET_ARCH: ${{ matrix.arch }}
      SCRIPT_DIR: "/work/voidpkgs/scripts"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare environment
        run: bash ${{ env.SCRIPT_DIR }}/set-environment.sh

      - name: Clone voidpkgs repo
        run: |
          mkdir -p /work
          cd /work
          git clone https://github.com/${{ github.repository_owner }}/voidpkgs.git

      - name: Build changed packages
        run: bash ${{ env.SCRIPT_DIR }}/build-packages.sh

      - name: Push binpkgs
        run: bash ${{ env.SCRIPT_DIR }}/push-repo.sh
