name: Build XBPS packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: voidlinux/void-glibc

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install git (necesario dentro del contenedor)
        run: xbps-install -Sy git

      - name: Detect changed templates
        id: changes
        run: |
          echo "changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f2 | sort -u)" >> $GITHUB_OUTPUT

      - name: Setup Void packages build environment
        run: |
          git clone https://github.com/void-linux/void-packages.git
          cd void-packages
          ./xbps-src binary-bootstrap

      - name: Build packages
        run: |
          cd void-packages
          for pkg in ${{ steps.changes.outputs.changed }}; do
            if [ -f "../srcpkgs/$pkg/template" ]; then
              cp -r ../srcpkgs/$pkg srcpkgs/
              ./xbps-src pkg $pkg
            fi
          done

      - name: Prepare repo
        run: |
          mkdir -p repo
          cp void-packages/hostdir/binpkgs/*/*.xbps repo/
          cp void-packages/hostdir/binpkgs/*/*.xbps.sig repo/
          xbps-rindex -a repo/*.xbps

      - name: Push repo branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin binpkgs || true
          git checkout -B binpkgs
          cp -r repo/* .
          git add .
          git commit -m "Update repo with new packages" || true
          git push origin binpkgs --force
